# **Курс "Програмування на мові Python"**

## **Практичне зайняття №10**

### Тема: "Лямбда-функції. Функції вищих порядків"

### **Завдання 1 (1 бал)**

Продавець роздрібного товару влаштовує розпродаж. Для всіх товарів знижка однакова - 60%. Щоб вивісити нові цінники, продавець хоче скласти таблицю, в якій для кожного товару буде підрахована його нова вартість та сума знижки.

Написати програму, яка буде генерувати таку таблицю. Вартість одиниць товарів до розпродажу подано у списку products_list. 

1. Для підрахунку невідомих значень повинні використовуватись вбудовані функції вищих порядків.

2. Вартість з урахуванням знижки та суми знижок для кожного товару повинні зберігатись у двох окремих списках. Порядок товарів у нових списках повинен бути такий самий, як і в списку products_list.

3. Кожне підраховане числове значення має бути округлене до сотих.

4. Дані повинні виводитись у вигляді:

**Discount table:**

**29.25 11.7 17.55**

**48.99 19.6 29.39**

**...**


products_list = [29.25, 48.99, 99.98, 124.65, 214.30, 543.90, 799.85]


In [1]:
import numpy as np

products_list = [29.25, 48.99, 99.98, 124.65, 214.30, 543.90, 799.85]
discount = []
for i in products_list:
    k = round(((i / 100) * 40), 2)
    discount.append(k)
total = []
for w in products_list:
    g = round(((w / 100) * 60), 2)
    total.append(g)
together = []
a = 0
for a in range(len(products_list)):
    elem = []
    elem.append(products_list[a])
    elem.append(discount[a])
    elem.append(total[a])
    together.append(elem)
print("Discount table: ")
print(np.array(together))

Discount table: 
[[ 29.25  11.7   17.55]
 [ 48.99  19.6   29.39]
 [ 99.98  39.99  59.99]
 [124.65  49.86  74.79]
 [214.3   85.72 128.58]
 [543.9  217.56 326.34]
 [799.85 319.94 479.91]]


### **Завдання 2 (2 бали)**

Зазвичай рік має 365 днів. Однак у високосні роки додається ще один день - 29 лютого. Правила визначення високосного року такі:

- Будь-який рік, що ділиться на 400 - високосний.

- З тих років, що залишились, будь-який рік, що ділиться на 100 - **не** високосний.

- З тих років, що залишились, будь-який рік, що ділиться на 4 - високосний.

- Усі інші роки, що залишились - **не** високосні.

1) Створіть функцію, в якій за допомогою вбудованих функцій вищих порядків будуть визначатися високосні роки серед перелічених років у списку years. Створена функція має повертати список високосних років.

2) Створіть функцію вищих порядків, яка прийматиме на вхід попередню функцію та визначатиме кількість днів у місяці. Також функція повинна приймати на вхід ще 2 параметри: ціле число від 1 до 12 (місяць) та рік, як ціле чотирицифрове число. Ці значення корисувач має вводити з клавіатури. Перевірку введених даних слід виконувати поза межами функцій.

In [2]:
import numpy as np

years = np.arange(1900, 2020+1, 1)
print(years)

for i in range (len(years)):
    if i % 400:
        print(years[i])
    else:
        print("")

[1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016 2017 2018 2019 2020]

1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977